language: cpp

jobs:
  include:
    - name: "OSX clang static library"
      os: osx
      env:
        - GENERATOR="Unix Makefiles"
        - SHARED=-DBUILD_SHARED_LIBS:BOOL=OFF
        - CTEST_OUTPUT_ON_FAILURE=1

    - name: "OSX clang shared library"
      os: osx
      env:
        - GENERATOR="Unix Makefiles"
        - SHARED=-DBUILD_SHARED_LIBS:BOOL=ON
        - CTEST_OUTPUT_ON_FAILURE=1

before_script:
  - mkdir build
  - cd build
  - cmake .. -G "${GENERATOR}" $SHARED

script: cmake --build . --target run_tests
